### ISSUE TITLE
Квантификатор

### ISSUE THREAD

**Issue by pecourses** [OlgaZP/js-dom-home#1]
https://github.com/OlgaZP/js-dom-home/blob/a4f0bfea9e3e6ff085336482fb06784557b59800/pages/dom2.html#L15
- Если я правильно понимаю идею, логично использовать короткий квантификатор ? вместо {0,1}.

**Comment by OlgaZP** [comment]
Да, согласна. Спасибо! Исправила и чуть оптимизировала.
